export const BARGRAPH_INDICATORS_LABEL = {
  ATTACK: "ATK",
  DEFENSE: "DEF",
  SPEED: "SPD",
  HP: "HP",
  SPECIAL_ATTACK: "SP-ATK"
};

export const BUTTON_CENTRAL_DIRECTIONS = {
  UP: "UP",
  DOWN: "DOWN",
  LEFT: "LEFT",
  RIGHT: "RIGHT"
};

export const BUTTON_SELECT = {
  SELECT: "SELECT"
};